// pages/kakamihitoshi/kakamihitoshi.js
Page({
     data: {
    image_array: [{
      src: "../../image/course/kakamihitoshi/001.jpg",
    }, {
      src: "../../image/course/kakamihitoshi/002.jpg",
    }, {
      src: "../../image/course/kakamihitoshi/003.jpg",
    }, {
      src: "../../image/course/kakamihitoshi/004.jpg",
    }, {
      src: "../../image/course/kakamihitoshi/005.jpg",
    }, {
      src: "../../image/course/kakamihitoshi/006.jpg",
    }, {
      src: "../../image/course/kakamihitoshi/007.jpg",
    }, {
      src: "../../image/course/kakamihitoshi/008.jpg",
    }, {
      src: "../../image/course/kakamihitoshi/009.jpg",
    }, {
      src: "../../image/course/kakamihitoshi/010.jpg",
    }, {
      src: "../../image/course/kakamihitoshi/011.jpg",
    }, {
      src: "../../image/course/kakamihitoshi/012.jpg",
    }, {
      src: "../../image/course/kakamihitoshi/013.jpg",
    }, {
      src: "../../image/course/kakamihitoshi/014.jpg",
    }, {
      src: "../../image/course/kakamihitoshi/015.jpg",
    }, {
      src: "../../image/course/kakamihitoshi/016.jpg",
    }, {
      src: "../../image/course/kakamihitoshi/017.jpg",
    }, {
      src: "../../image/course/kakamihitoshi/018.jpg",
    }, {
      src: "../../image/course/kakamihitoshi/019.jpg",
    }, {
      src: "../../image/course/kakamihitoshi/020.jpg",
    }, {
      src: "../../image/course/kakamihitoshi/021.jpg",
    }, {
      src: "../../image/course/kakamihitoshi/022.jpg",
    }, {
      src: "../../image/course/kakamihitoshi/023.jpg",
    }, {
      src: "../../image/course/kakamihitoshi/024.jpg",
    }, {
      src: "../../image/course/kakamihitoshi/025.jpg",
    }, {
      src: "../../image/course/kakamihitoshi/026.jpg",
    }, {
      src: "../../image/course/kakamihitoshi/027.jpg",
    }, {
      src: "../../image/course/kakamihitoshi/028.jpg",
    }, {
      src: "../../image/course/kakamihitoshi/029.jpg",
    }, {
      src: "../../image/course/kakamihitoshi/030.jpg",
    }, {
      src: "../../image/course/kakamihitoshi/031.jpg",
    }, {
      src: "../../image/course/kakamihitoshi/032.jpg",
    }, {
      src: "../../image/course/kakamihitoshi/033.jpg",
    }, {
      src: "../../image/course/kakamihitoshi/034.jpg",
    }, {
      src: "../../image/course/kakamihitoshi/035.jpg",
    }, {
      src: "../../image/course/kakamihitoshi/036.jpg",
    }, {
      src: "../../image/course/kakamihitoshi/037.jpg",
    }, {
      src: "../../image/course/kakamihitoshi/038.jpg",
    }, {
      src: "../../image/course/kakamihitoshi/039.jpg",
    }, {
      src: "../../image/course/kakamihitoshi/040.jpg",
    }, {
      src: "../../image/course/kakamihitoshi/041.jpg",
    }, {
      src: "../../image/course/kakamihitoshi/042.jpg",
    }, {
      src: "../../image/course/kakamihitoshi/043.jpg",
    }, {
      src: "../../image/course/kakamihitoshi/044.jpg",
    }, {
      src: "../../image/course/kakamihitoshi/045.jpg",
    }, {
      src: "../../image/course/kakamihitoshi/046.jpg",
    }, {
      src: "../../image/course/kakamihitoshi/047.jpg",
    }, {
      src: "../../image/course/kakamihitoshi/048.jpg",
    }, {
      src: "../../image/course/kakamihitoshi/049.jpg",
    }, {
      src: "../../image/course/kakamihitoshi/050.jpg",
    }, {
      src: "../../image/course/kakamihitoshi/051.jpg",
    }, {
      src: "../../image/course/kakamihitoshi/052.jpg",
    }, {
      src: "../../image/course/kakamihitoshi/053.jpg",
    }, {
      src: "../../image/course/kakamihitoshi/054.jpg",
    }, {
      src: "../../image/course/kakamihitoshi/055.jpg",
    }, {
      src: "../../image/course/kakamihitoshi/056.jpg",
    }, {
      src: "../../image/course/kakamihitoshi/057.jpg",
    }, {
      src: "../../image/course/kakamihitoshi/058.jpg",
    }, {
      src: "../../image/course/kakamihitoshi/059.jpg",
    }, {
      src: "../../image/course/kakamihitoshi/030.jpg",
    }, {
      src: "../../image/course/kakamihitoshi/061.jpg",
    }, {
      src: "../../image/course/kakamihitoshi/062.jpg",
    }, {
      src: "../../image/course/kakamihitoshi/063.jpg",
    }, {
      src: "../../image/course/kakamihitoshi/064.jpg",
    }, {
      src: "../../image/course/kakamihitoshi/065.jpg",
    }, {
      src: "../../image/course/kakamihitoshi/066.jpg",
    }, {
      src: "../../image/course/kakamihitoshi/067.jpg",
    }, {
      src: "../../image/course/kakamihitoshi/068.jpg",
    }, {
      src: "../../image/course/kakamihitoshi/069.jpg",
    }, {
      src: "../../image/course/kakamihitoshi/070.jpg",
    }, {
      src: "../../image/course/kakamihitoshi/071.jpg",
    }, {
      src: "../../image/course/kakamihitoshi/072.jpg",
    }, {
      src: "../../image/course/kakamihitoshi/073.jpg",
    }, {
      src: "../../image/course/kakamihitoshi/074.jpg",
    }, {
      src: "../../image/course/kakamihitoshi/075.jpg",
    }, {
      src: "../../image/course/kakamihitoshi/076.jpg",
    }, {
      src: "../../image/course/kakamihitoshi/077.jpg",
    }, {
      src: "../../image/course/kakamihitoshi/078.jpg",
    }, {
      src: "../../image/course/kakamihitoshi/079.jpg",
    }, {
      src: "../../image/course/kakamihitoshi/080.jpg",
    }, {
      src: "../../image/course/kakamihitoshi/081.jpg",
    }, {
      src: "../../image/course/kakamihitoshi/082.jpg",
    }, {
      src: "../../image/course/kakamihitoshi/083.jpg",
    }, {
      src: "../../image/course/kakamihitoshi/084.jpg",
    }, {
      src: "../../image/course/kakamihitoshi/085.jpg",
    }, {
      src: "../../image/course/kakamihitoshi/086.jpg",
    }, {
      src: "../../image/course/kakamihitoshi/087.jpg",
    }, {
      src: "../../image/course/kakamihitoshi/088.jpg",
    }, {
      src: "../../image/course/kakamihitoshi/089.jpg",
    }, {
      src: "../../image/course/kakamihitoshi/090.jpg",
    }, {
      src: "../../image/course/kakamihitoshi/091.jpg",
    }, {
      src: "../../image/course/kakamihitoshi/092.jpg",
    }, {
      src: "../../image/course/kakamihitoshi/093.jpg",
    }, {
      src: "../../image/course/kakamihitoshi/094.jpg",
    }, {
      src: "../../image/course/kakamihitoshi/095.jpg",
    }, {
      src: "../../image/course/kakamihitoshi/096.jpg",
    }, {
      src: "../../image/course/kakamihitoshi/097.jpg",
    }, {
      src: "../../image/course/kakamihitoshi/098.jpg",
    }, {
      src: "../../image/course/kakamihitoshi/099.jpg",
    }, {
      src: "../../image/course/kakamihitoshi/090.jpg",
    }, {
      src: "../../image/course/kakamihitoshi/100.jpg",
    }, {
      src: "../../image/course/kakamihitoshi/101.jpg",
    }, {
      src: "../../image/course/kakamihitoshi/102.jpg",
    }, {
      src: "../../image/course/kakamihitoshi/103.jpg",
    }, {
      src: "../../image/course/kakamihitoshi/104.jpg",
    }, {
      src: "../../image/course/kakamihitoshi/105.jpg",
    }, {
      src: "../../image/course/kakamihitoshi/106.jpg",
    }, {
      src: "../../image/course/kakamihitoshi/107.jpg",
    }, {
      src: "../../image/course/kakamihitoshi/108.jpg",
    }, {
      src: "../../image/course/kakamihitoshi/109.jpg",
    }, {
      src: "../../image/course/kakamihitoshi/100.jpg",
    }, {
      src: "../../image/course/kakamihitoshi/111.jpg",
    }, {
      src: "../../image/course/kakamihitoshi/112.jpg",
    }, {
      src: "../../image/course/kakamihitoshi/113.jpg",
    }, {
      src: "../../image/course/kakamihitoshi/114.jpg",
    }, {
      src: "../../image/course/kakamihitoshi/115.jpg",
    }, {
      src: "../../image/course/kakamihitoshi/116.jpg",
    }, {
      src: "../../image/course/kakamihitoshi/117.jpg",
    }, {
      src: "../../image/course/kakamihitoshi/118.jpg",
    }, {
      src: "../../image/course/kakamihitoshi/119.jpg",
    }, {
      src: "../../image/course/kakamihitoshi/110.jpg",
    }, {
      src: "../../image/course/kakamihitoshi/121.jpg",
    }, {
      src: "../../image/course/kakamihitoshi/122.jpg",
    }, {
      src: "../../image/course/kakamihitoshi/123.jpg",
    }, {
      src: "../../image/course/kakamihitoshi/124.jpg",
    }, {
      src: "../../image/course/kakamihitoshi/125.jpg",
    }, {
      src: "../../image/course/kakamihitoshi/126.jpg",
    }, {
      src: "../../image/course/kakamihitoshi/127.jpg",
    }, {
      src: "../../image/course/kakamihitoshi/128.jpg",
    }],
  },
  onLoad:function(options){
    // 页面初始化 options为页面跳转所带来的参数
  },
  onReady:function(){
    // 页面渲染完成
  },
  onShow:function(){
    // 页面显示
  },
  onHide:function(){
    // 页面隐藏
  },
  onUnload:function(){
    // 页面关闭
  }
})